version: "3.8"

services:
  gateway-east:
    image: 4757/pq-strongswan:latest
    container_name: gateway-east
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    stdin_open: true
    tty: true
    volumes:
      - ./gateway-east/swanctl.conf:/etc/swanctl/swanctl.conf
      - ./gateway-east/east/:/etc/swanctl/
      - ./strongswan.conf:/etc/strongswan.conf
      - ./scripts:/scripts
    command: "./charon"
    networks:
      internet:
        ipv4_address: 192.168.0.2
      east-lan:
        ipv4_address: 10.1.0.2

  gateway-west:
    image: 4757/pq-strongswan:latest
    container_name: gateway-west
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    stdin_open: true
    tty: true
    volumes:
      - ./gateway-west/swanctl.conf:/etc/swanctl/swanctl.conf
      - ./gateway-west/west/:/etc/swanctl/
      - ./strongswan.conf:/etc/strongswan.conf
      - ./scripts:/scripts
    command: "./charon"
    networks:
      internet:
        ipv4_address: 192.168.0.3
      west-lan:
        ipv4_address: 10.2.0.2

  client-east:
    image: alpine:latest
    container_name: client-east
    depends_on:
      - gateway-east
    cap_add:
      - NET_ADMIN
    command: sh -c "ip route del default && ip route add default via 10.1.0.2 && tail -f /dev/null"
    networks:
      east-lan:
        ipv4_address: 10.1.0.10

  client-west:
    image: alpine:latest
    container_name: client-west
    depends_on:
      - gateway-west
    cap_add:
      - NET_ADMIN
    command: sh -c "ip route del default && ip route add default via 10.2.0.2 && tail -f /dev/null"
    networks:
      west-lan:
        ipv4_address: 10.2.0.10

  carol:
    image: 4757/pq-strongswan:latest
    container_name: carol
    privileged: true
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    volumes:
      - ./rw/carol:/etc/swanctl/
      - ./strongswan.conf:/etc/strongswan.conf
    command: "./charon"
    networks:
      east-lan:
        ipv4_address: 10.1.0.100

  bob:
    image: 4757/pq-strongswan:latest
    container_name: bob
    privileged: true
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    volumes:
      - ./rw/bob:/etc/swanctl/
      - ./strongswan.conf:/etc/strongswan.conf
    command: "./charon"
    networks:
      west-lan:
        ipv4_address: 10.2.0.100

networks:
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

  east-lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24

  west-lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
