connections {
    net-net {
        remote_addrs = 192.168.0.4

        local {
            auth = pubkey
            certs = eastCert.pem
            id = east.synergyquantum.in
        }
        remote {
            auth = pubkey
            id = west.synergyquantum.in
            cacerts = caCert.pem
        }

        children {
            net {
                local_ts = 192.168.101.0/24
                remote_ts = 192.168.100.0/24
                start_action = start
                dpd_action = restart

                esp_proposals = aes256gcm16-x25519-ke1_kyber3-ke2_bike3-ke3_hqc3
            }
        }

        version = 2
        proposals = aes256gcm16-prfsha384-x25519-modp3072-ke1_kyber3-ke2_bike3-ke3_hqc3
        reauth_time = 0
    }
}


